version: "3"

services:
    sokoban-app:
        build:
            context: .
        ports:
            ["5000:5000"]
        restart: always
        networks:
            [awesome]

    sokoban-api:
        build:
            context: ./api
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://chicago:password@postgres:5432/sokobandb
            NODE_ENV: development
            PORT: 8000
        ports:
            ["8000:8000"]
        restart: always
        networks:
            [awesome]

    postgres:
        hostname: postgres
        container_name: postgres
        image: postgres:9.6.5-alpine
        ports:
            ['5432:5432']
        volumes:
            - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always
        environment:
            POSTGRES_USER: chicago
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sokobandb
        networks:
            [awesome]

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            ["8088:80"]
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            [awesome]

volumes:
    pgadmin-data:

networks:
    awesome:
        driver: bridge
