name: CI
on:
    push:
        branches:
            - feature/game#74-CI-CD
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd game
                      git pull
                      docker-compose up --detach
                      npm i
                      npm run spa-build
                      rm -rf /var/www/html/*
                      cp -r dist/* /var/www/html/
